name: TensoRF
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - configargparse
    - imageio-ffmpeg
    - kornia
    - lpips
    - opencv-python
    - scikit-image
    - tensorboard
    - tqdm  
